### PR TITLE
Convert to Exponent

### PR DESCRIPTION
**Pull request by brentvatne**
You can try it out at https://getexponent.com/@community/emoji-feedback :)

I used the `exp convert` tool described here: https://docs.getexponent.com/versions/v10.0.0/introduction/faq.html#how-do-i-get-my-existing-react-native-project-running-with-exponent

Would be very cool to use this for future UI challenges! It's a great way to share your React Native code -- eg: https://twitter.com/janicduplessis/status/775820776708698113

(I'm biased, I work at Exponent, but probably a lot more people will try out your stuff if you do this because it just becomes a tap away once they have Exponent installed, which even if they don't is easier than cloning / building etc :>)

### CODE REVIEW

**Comment by mastermoo** [comment]
@brentvatne I'm trusting you in exponent. I hope my time is well invested.. :)

**Comment by brentvatne** [comment]
:) @mastermoo I think you'll be happy with it. let me know if you have any questions, happy to help.

worst case you can always back out to vanilla react-native, but that shouldn't be necessary :P

**Comment by brentvatne** [comment]
If it adds to our credibility at all, we just finished YC and uh TechCrunch thought we were ok - https://techcrunch.com/gallery/yc-demo-day/slide/8/ -- we're not going anywhere and just keep getting better ;)

**Comment by mastermoo** [comment]
oh, I underestimated exponent quite a bit. thats good to hear. thanks for your help @brentvatne!

**Pull request merged**
